DROP DATABASE IF EXISTS msds;
CREATE DATABASE msds;

DROP TABLE IF EXISTS msdsCourseCatalog;

\c msds;

CREATE TABLE  msdsCourseCatalog(
    CID VARCHAR(10) PRIMARY KEY NOT NULL,
    CNAME VARCHAR(100),
    CPREREQ VARCHAR(10)
);